#!/usr/bin/env python3
import requests, json, sys
from youdao import translateEnglish
from fanti import Simplified2Traditional

def translate(text):
  data = {
    'gb': Simplified2Traditional(text),
    'en': translateEnglish(text)
  }
  params = {}
  params[text] = data
  print(params)


#inputText = input('please write your word: ')
translate(sys.argv[1])
