#!/usr/bin/env python3
import requests, json, sys
from langconv import *

def Simplified2Traditional(sentence):
    sentence = Converter('zh-hant').convert(sentence)
    return sentence

def translate(text):
  url = 'http://fanyi.youdao.com/openapi.do?keyfrom=node-fanyi&key=110811608&type=data&doctype=json&version=1.1&q={}'.format(text)
  response = requests.get(url).json()
  data = {
    'gb': Simplified2Traditional(response['query']),
    'en': response['translation'][0].replace('"', "'")
  }
  print({
    response['query']: data
  })


#inputText = input('please write your word: ')
translate(sys.argv[1])
