#!/usr/bin/env python3
import requests, json, sys
from langconv import *
from youdao import translateEn
from baidu import translateEnglish
def Simplified2Traditional(sentence):
    sentence = Converter('zh-hant').convert(sentence)
    return sentence

def translate(text):
  data = {
    'gb': Simplified2Traditional(text),
    # 'en': translateEn(text)
    'en': translateEnglish(text)
  }
  params = {}
  params[text] = data
  print(params)


#inputText = input('please write your word: ')
translate(sys.argv[1])
