export const zh = {
  '个': '个',
  '按': '按',
  '或': '或',
  '条': '条',
  '等': '等',
  '这个': '这个',
  '个数': '个数',
  '保留': '保留',
  '数值': '数值',
  '已选': '已选',
  '设置': '设置',
  '请选择': '请选择',
  '分类': '分类',
  '更新': '更新',
  '失败': '失败',
  '成功': '成功',
  '删除': '删除',
  '确定': '确定',
  '取消': '取消',
  '修改': '修改',
  '未合并': '未合并',
  '项目': '项目',
  '计划': '计划',
  '所属计划': '所属计划',
  '单元': '单元',
  '单元名称': '单元名称',
  '创意': '创意',
  '创意尺寸': '创意尺寸',
  '元件': '元件',
  '元素': '元素',
  '类型': '类型',
  '全选': '全选',
  '相似': '相似',
  '曝光': '曝光',
  '点击': '点击',
  '指标': '指标',
  '方式': '方式',
  '淘汰': '淘汰',
  '已合并': '已合并',
  '请求成功': '请求成功',
  '过滤条件': '过滤条件',
  '优化频率': '优化频率',
  '保留设置': '保留设置',
  '暂停方案': '暂停方案',
  '末尾淘汰': '末尾淘汰',
  '相对阈值淘汰': '相对阈值淘汰',
  '绝对阈值淘汰': '绝对阈值淘汰',
  '阈值': '阈值',
  '默认': '默认',
  '大于': '大于',
  '等于': '等于',
  '小时': '小时',
  '分钟': '分钟',
  '比例': '比例',
  '保留个数': '保留个数',
  '保留比例': '保留比例',
  '按计划筛选': '按计划筛选',
  '按项目筛选': '按项目筛选',
  '请选择要修改的元件': '请选择要修改的元件',
  '请输入关键字按Enter搜索': '请输入关键字按Enter搜索',
  '发生异常：分类ID不存在！': '发生异常：分类ID不存在！',
  '标签': '标签',
  '创意包管理': '创意包管理',
  '提示': '提示',
  '全部': '全部',
  '开启': '开启',
  '暂停': '暂停',
  '正在': '正在',
  '准备': '准备',
  '完成': '完成',
  '添加': '添加',
  '推送': '推送',
  '操作': '操作',
  '状态': '状态',
  '错误': '错误',
  '请输入': '请输入',
  '投放渠道': '投放渠道',
  '创意包名称': '创意包名称',
  '计划数': '计划数',
  '返回旧版': '返回旧版',
  '新建': '新建',
  '创建时间': '创建时间',
  '广告位': '广告位',
  '创意包': '创意包',
  '组合数': '组合数',
  '创意预估': '创意预估',
  '单元数': '单元数',
  '导入单元': '导入单元',
  '策略ID': '策略ID',
  '预览数据': '预览数据',
  '上传文件': '上传文件',
  '上传成功': '上传成功',
  '最近推送': '最近推送',
  '预算/出价': '预算/出价',
  '点击上传': '点击上传',
  '上一步': '上一步',
  '批量操作': '批量操作',
  '继续': '继续',
  '下一步': '下一步',
  '名称': '名称',
  '文案包': '文案包',
  '保存': '保存',
  '计划名称': '计划名称',
  '以上计划': '以上计划',
  '文案创意': '文案创意',
  '已取消删除': '已取消删除',
  '不能为空': '不能为空',
  '请选择记录': '请选择记录',
  '推广辅助类型': '推广辅助类型',
  '将文件拖到此处': '将文件拖到此处',
  '您还没有上传文件哟~': '您还没有上传文件哟~',
  '请您至少选择一个单元~': '请您至少选择一个单元~',
  '请输入创意包创意名称/ID': '请输入创意包创意名称/ID',
  '请选择需要操作的选项': '请选择需要操作的选项',
  '此操作将批量删除以上': '此操作将批量删除以上',
  '请选择删除的选项': '请选择删除的选项',
  '文案包管理，当您在为每个广告位搭配创意时，可为信息流广告位，可直接选择已创建的文案创意': '文案包管理，当您在为每个广告位搭配创意时，可为信息流广告位，可直接选择已创建的文案创意',
  '导入从reachmax导出订单excel，如：示例所示，系统将根据表格的字段，自动生成计划和单元': '导入从reachmax导出订单excel，如：示例所示，系统将根据表格的字段，自动生成计划和单元',
  '1个广告位生成1个创意包,请为每个广告位添加素材，然后将素材推送到该广告位的计划上！': '1个广告位生成1个创意包,请为每个广告位添加素材，然后将素材推送到该广告位的计划上！',
  '支持excel和CSV文件最多上传1个文件，默认识别第一个sheet文件': '支持excel和CSV文件最多上传1个文件，默认识别第一个sheet文件',
  '其他': '其他'
}
export const en = {
  '个': 'individual',
  '按': 'Press',
  '或': 'or',
  '条': 'strip',
  '等': 'etc.',
  '这个': 'this',
  '个数': 'Number',
  '保留': 'Retain',
  '数值': 'numerical value',
  '已选': 'Selected',
  '设置': 'Set up',
  '请选择': 'Please choose',
  '分类': 'classification',
  '更新': 'To update',
  '失败': 'fail',
  '成功': 'Success',
  '删除': 'delete',
  '确定': 'Sure?',
  '取消': 'cancel',
  '修改': 'modify',
  '未合并': 'Unconsolidated',
  '项目': 'project',
  '计划': 'plan',
  '所属计划': 'Planned ownership',
  '单元': 'unit',
  '单元名称': 'Unit name',
  '创意': 'Originality',
  '创意尺寸': 'Creative size',
  '元件': 'element',
  '元素': 'element',
  '类型': 'type',
  '全选': 'All election',
  '相似': 'Be similar',
  '曝光': 'exposure',
  '点击': 'click',
  '指标': 'index',
  '方式': 'mode',
  '淘汰': 'eliminate',
  '已合并': 'Merged',
  '请求成功': 'Request successful',
  '过滤条件': 'Filter condition',
  '优化频率': 'Optimized frequency',
  '保留设置': 'Save settings',
  '暂停方案': 'Suspension scheme',
  '末尾淘汰': 'Elimination at the end',
  '相对阈值淘汰': 'Relative threshold elimination',
  '绝对阈值淘汰': 'Absolute Threshold Elimination',
  '阈值': 'threshold',
  '默认': 'default',
  '大于': 'greater than',
  '等于': 'Be equal to',
  '小时': 'hour',
  '分钟': 'Minute',
  '比例': 'Proportion',
  '保留个数': 'Reserved number',
  '保留比例': 'Retention ratio',
  '按计划筛选': 'Screening on schedule',
  '按项目筛选': 'Screening by project',
  '请选择要修改的元件': 'Please select the component you want to modify',
  '请输入关键字按Enter搜索': 'Please enter keywords and press Enter to search',
  '发生异常：分类ID不存在！': 'Abnormal: Classification ID does not exist!',
  '标签': 'Label',
  '创意包管理': 'Creative Package Management',
  '提示': 'Tips',
  '全部': 'whole',
  '开启': 'open',
  '暂停': 'suspend',
  '正在': 'Being',
  '准备': 'Get ready',
  '完成': 'complete',
  '添加': 'Add to',
  '推送': 'Push',
  '操作': 'operation',
  '状态': 'state',
  '错误': 'error',
  '请输入': 'Please input',
  '投放渠道': 'Delivery channel',
  '创意包名称': 'Name of Creative Package',
  '计划数': 'Plan number',
  '返回旧版': 'Return to old version',
  '新建': 'Newly build',
  '创建时间': 'Creation time',
  '广告位': 'Advertising position',
  '创意包': 'Creative package',
  '组合数': 'Combinatorial number',
  '创意预估': 'Creative prediction',
  '单元数': 'Cell number',
  '导入单元': 'Import unit',
  '策略ID': 'Strategy ID',
  '预览数据': 'preview data',
  '上传文件': 'Upload files',
  '上传成功': 'Upload success',
  '最近推送': 'Recent push',
  '预算/出价': 'Budget/Bid',
  '点击上传': 'Click upload',
  '上一步': 'Previous step',
  '批量操作': 'Batch operation',
  '继续': 'Continue',
  '下一步': 'Next step',
  '名称': 'Name',
  '文案包': 'Copybag',
  '保存': 'Preservation',
  '计划名称': 'Plan name',
  '以上计划': 'Above plan',
  '文案创意': 'Copywriting creativity',
  '已取消删除': 'Canceled deletion',
  '不能为空': 'Can not be empty',
  '请选择记录': 'Please select Records',
  '推广辅助类型': 'Extension of auxiliary types',
  '将文件拖到此处': 'Drag the file here',
  '您还没有上传文件哟~': 'You haven\'t uploaded the file yet.~',
  '请您至少选择一个单元~': 'Please choose at least one unit.~',
  '请输入创意包创意名称/ID': 'Please enter the Creative Package Creative Name/ID',
  '请选择需要操作的选项': 'Please select the options that need to be operated on',
  '此操作将批量删除以上': 'This operation will delete the batch above',
  '请选择删除的选项': 'Please select the option to delete',
  '文案包管理，当您在为每个广告位搭配创意时，可为信息流广告位，可直接选择已创建的文案创意': 'Text Packet Management, when you match creativity for each advertising space, you can directly select the created text ideas for the information flow advertising space.',
  '导入从reachmax导出订单excel，如：示例所示，系统将根据表格的字段，自动生成计划和单元': 'Import export order excel from reachmax, as shown in the example, the system will automatically generate plans and units according to the fields of the table',
  '1个广告位生成1个创意包,请为每个广告位添加素材，然后将素材推送到该广告位的计划上！': 'One advertising space generates a creative package. Please add material for each advertising space, and then push the material to the advertising space's plan!',
  '支持excel和CSV文件最多上传1个文件，默认识别第一个sheet文件': 'Supports uploading up to one file from excel and CSV files, and identifies the first sheet file by default.',
  '其他': 'Other'
}
export const GB = {
  '个': '個',
  '按': '按',
  '或': '或',
  '条': '條',
  '等': '等',
  '这个': '這個',
  '个数': '個數',
  '保留': '保留',
  '数值': '數值',
  '已选': '已選',
  '设置': '設置',
  '请选择': '請選擇',
  '分类': '分類',
  '更新': '更新',
  '失败': '失敗',
  '成功': '成功',
  '删除': '刪除',
  '确定': '確定',
  '取消': '取消',
  '修改': '修改',
  '未合并': '未合併',
  '项目': '項目',
  '计划': '計劃',
  '所属计划': '所屬計劃',
  '单元': '單元',
  '单元名称': '單元名稱',
  '创意': '創意',
  '创意尺寸': '創意尺寸',
  '元件': '元件',
  '元素': '元素',
  '类型': '類型',
  '全选': '全選',
  '相似': '相似',
  '曝光': '曝光',
  '点击': '點擊',
  '指标': '指標',
  '方式': '方式',
  '淘汰': '淘汰',
  '已合并': '已合併',
  '请求成功': '請求成功',
  '过滤条件': '過濾條件',
  '优化频率': '優化頻率',
  '保留设置': '保留設置',
  '暂停方案': '暫停方案',
  '末尾淘汰': '末尾淘汰',
  '相对阈值淘汰': '相對閾值淘汰',
  '绝对阈值淘汰': '絕對閾值淘汰',
  '阈值': '閾值',
  '默认': '默認',
  '大于': '大於',
  '等于': '等於',
  '小时': '小時',
  '分钟': '分鐘',
  '比例': '比例',
  '保留个数': '保留個數',
  '保留比例': '保留比例',
  '按计划筛选': '按計劃篩選',
  '按项目筛选': '按項目篩選',
  '请选择要修改的元件': '請選擇要修改的元件',
  '请输入关键字按Enter搜索': '請輸入關鍵字按Enter搜索',
  '发生异常：分类ID不存在！': '發生異常：分類ID不存在！',
  '标签': '標簽',
  '创意包管理': '創意包管理',
  '提示': '提示',
  '全部': '全部',
  '开启': '開啟',
  '暂停': '暫停',
  '正在': '正在',
  '准备': '準備',
  '完成': '完成',
  '添加': '添加',
  '推送': '推送',
  '操作': '操作',
  '状态': '狀態',
  '错误': '錯誤',
  '请输入': '請輸入',
  '投放渠道': '投放渠道',
  '创意包名称': '創意包名稱',
  '计划数': '計劃數',
  '返回旧版': '返回舊版',
  '新建': '新建',
  '创建时间': '創建時間',
  '广告位': '廣告位',
  '创意包': '創意包',
  '组合数': '組合數',
  '创意预估': '創意預估',
  '单元数': '單元數',
  '导入单元': '導入單元',
  '策略ID': '策略ID',
  '预览数据': '預覽數據',
  '上传文件': '上傳文件',
  '上传成功': '上傳成功',
  '最近推送': '最近推送',
  '预算/出价': '預算/出價',
  '点击上传': '點擊上傳',
  '上一步': '上一步',
  '批量操作': '批量操作',
  '继续': '繼續',
  '下一步': '下一步',
  '名称': '名稱',
  '文案包': '文案包',
  '保存': '保存',
  '计划名称': '計劃名稱',
  '以上计划': '以上計劃',
  '文案创意': '文案創意',
  '已取消删除': '已取消刪除',
  '不能为空': '不能為空',
  '请选择记录': '請選擇記錄',
  '推广辅助类型': '推廣輔助類型',
  '将文件拖到此处': '將文件拖到此處',
  '您还没有上传文件哟~': '您還沒有上傳文件喲~',
  '请您至少选择一个单元~': '請您至少選擇一個單元~',
  '请输入创意包创意名称/ID': '請輸入創意包創意名稱/ID',
  '请选择需要操作的选项': '請選擇需要操作的選項',
  '此操作将批量删除以上': '此操作將批量刪除以上',
  '请选择删除的选项': '請選擇刪除的選項',
  '文案包管理，当您在为每个广告位搭配创意时，可为信息流广告位，可直接选择已创建的文案创意': '文案包管理，當您在為每個廣告位搭配創意時，可為信息流廣告位，可直接選擇已創建的文案創意',
  '导入从reachmax导出订单excel，如：示例所示，系统将根据表格的字段，自动生成计划和单元': '導入從reachmax導出訂單excel，如：示例所示，系統將根據表格的字段，自動生成計劃和單元',
  '1个广告位生成1个创意包,请为每个广告位添加素材，然后将素材推送到该广告位的计划上！': '1個廣告位生成1個創意包,請為每個廣告位添加素材，然後將素材推送到該廣告位的計划上！',
  '支持excel和CSV文件最多上传1个文件，默认识别第一个sheet文件': '支持excel和CSV文件最多上傳1個文件，默認識別第一個sheet文件',
  '其他': '其他'
}
export default {zh, en, GB}
